os:
- linux
language: node_js
node_js:
- 10.6.0
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - /^greenkeeper/.*$/
jobs:
  include:
  - env: MODE=lint-lib
  - env: MODE=test-lib
  - env: MODE=lint-demo
  - env: MODE=test-demo
  - env: DEPLOY_MODE=build-artifacts
    if: type = push AND branch = master
  # For now, changelog will be manually edited
  # - env: DEPLOY_MODE=changelog
  #  if: tag IS present
  # Don't deploy docs on PRs
  - env: DEPLOY_MODE=docs
    if: type = push AND branch = master
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g @angular/cli
- ng --version
install:
- npm install
script:
- "./scripts/travis.sh"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false