os:
- linux
language: node_js
node_js: lts/*
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  # Allow testing on greenkeeper branches
  # TODO: Remove this line
  - /^greenkeeper/.*$/
stages:
  - lint
  - test
  # Only allow building if the branch is master and is pushed
  - name: build
    if: type = push AND branch = master
jobs:
  include:
  - stage: lint
    env: MODE=lint-lib
    name: "Library linting"
  - env: MODE=lint-demo
    name: "Demo linting"
  - stage: test
    env: MODE=test-lib
    name: "Library testing"
  - stage: build
    env: DEPLOY_MODE=build-artifacts
    name: "Build artifacts"
    # Don't deploy docs on PRs
  - env: DEPLOY_MODE=docs
    name: "Documentation"
install:
- npm install
script:
- "./scripts/travis.sh"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
