
os:
  - linux
language: node_js
node_js:
  - "10.1.0"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
    - node_modules
branches:
  only:
  - master
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Globally install Angular CLI
  - npm install -g @angular/cli
  # Output Angular CLI version
  - ng --version
install:
  - npm install
script:
  - ng test --watch=false
  - ng lint
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false