
os:
  - linux
language: node_js
node_js:
  - "10.1.0"
# Addons
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
    - node_modules
branches:
  only:
  - master

jobs:
  include:
    # Lint the library
    - env: "MODE=lint-lib"
    # Test the library
    - env: "MODE=test-lib"
    # Lint the demo
    - env: "MODE=lint-demo"
    # Test the demo
    - env: "MODE=test-demo"
    # Build artifacts
    - env: "DEPLOY_MODE=build-artifacts"
      if: type = push
    # Deploy changelog once a tag is published
    - env: "DEPLOY_MODE=changelog"
      if: tag IS present
    # Deploy docs once a tag is published
    - env: "DEPLOY_MODE=docs-tag"
      if: tag IS present
    - env: "DEPLOY_MODE=docs-master"
before_script:
  # Workaround for permission problems
  # See https://github.com/travis-ci/travis-ci/issues/9024 for more info
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Globally install Angular CLI
  - npm install -g @angular/cli
  # Output Angular CLI version
  - ng --version
install:
  - npm install
script:
  - ./scripts/travis.sh
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false